package:
  name: recsys_slates_dataset
  version: 0.0.6
source:
  sha256: 0ebd0a47a9ab661b57f530abfea05e5b0e4a43d436caaabd2845a12d22967b34
  url: https://files.pythonhosted.org/packages/66/84/b6860cf27032d1249828a953d767ab7b0ea637e62c7c66500c5aee92b61c/recsys_slates_dataset-0.0.6.tar.gz
about:
  dev_url: http://opensource.finn.no
  doc_url: http://opensource.finn.no
  home: http://opensource.finn.no
  license: Apache Software
  license_family: APACHE
  summary: Recommender Systems Dataset from FINN.no containing the presented items
    and whether and what the user clicked on.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - finn-no
requirements:
  host:
  - pip
  - python
  - packaging
  - requests>=2.25.1
  - numpy>=1.19.5
  - pandas>=1.0.5
  - torch>=1.9.0
  - PyYAML==5.4.1
  - googledrivedownloader==0.4
  - pytorch-lightning==1.4.1
  run:
  - pip
  - python
  - packaging
  - requests>=2.25.1
  - numpy>=1.19.5
  - pandas>=1.0.5
  - torch>=1.9.0
  - PyYAML==5.4.1
  - googledrivedownloader==0.4
  - pytorch-lightning==1.4.1
test:
  imports:
  - recsys_slates_dataset
