package:
  name: recsys_slates_dataset
  version: 0.0.3
source:
  sha256: 8c990a3f47a5286d631a0073292e12e908b39f7086291a4cb5c5ca350f60a323
  url: https://files.pythonhosted.org/packages/2a/52/0796014837643169b4ce1b57f2c09b61b8e3be9efbe860295c5f995e0c9a/recsys_slates_dataset-0.0.3.tar.gz
about:
  dev_url: http://opensource.finn.no
  doc_url: http://opensource.finn.no
  home: http://opensource.finn.no
  license: Apache Software
  license_family: APACHE
  summary: Recommender Systems Dataset from FINN.no containing the presented items
    and whether and what the user clicked on.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - finn-no
requirements:
  host:
  - pip
  - python
  - packaging
  - requests>=2.25.1
  - numpy>=1.19.5
  - pandas>=1.0.5
  - torch>=1.6.0
  - PyYAML==5.4.1
  - googledrivedownloader==0.4
  run:
  - pip
  - python
  - packaging
  - requests>=2.25.1
  - numpy>=1.19.5
  - pandas>=1.0.5
  - torch>=1.6.0
  - PyYAML==5.4.1
  - googledrivedownloader==0.4
test:
  imports:
  - recsys_slates_dataset
